In [2]:
import numpy as np
import pandas as pd

# __Load Dataset__

In [3]:
df = pd.read_csv(r'C:\Users\ibad\Desktop\NLP_Notes\projects\project1\data\tmdb_9000_top_rated.csv')

# __EDA Process__

In [4]:
# Understanding first five rows
df.head()

,movie,description,gener
0,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...","Animation, Action, Adventure, Fantasy"
1,Accidental Partners,Two women discover they were both scammed by t...,"Comedy, Romance"
2,Swapped,"A small woodland creature and a majestic bird,...","Adventure, Animation, Family, Fantasy"
3,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
4,Michael,"The story of Michael Jackson, one of the most ...","Music, Drama"

In [5]:
# Last 5 rows
df.tail()

,movie,description,gener
8995,Open Season: Scared Silly,The humans and animals believe a werewolf is o...,"Animation, Comedy, Family, Adventure, TV Movie"
8996,The Dyatlov Pass Incident,"In February of 1959, nine Russian hikers ventu...","Thriller, Mystery"
8997,Ri¢hie Ri¢h,"Billionaire heir Richie Rich has it all, inclu...","Comedy, Family"
8998,24 Hours to Live,An assassin seeks redemption after being given...,"Action, Science Fiction, Thriller, Mystery"
8999,iBoy,"After an accident, Tom wakes from a coma to di...","Action, Science Fiction"

In [6]:
# Checking random rows
df.sample(5)

,movie,description,gener
3265,Searching for Bobby Fischer,A seven-year-old chess prodigy refuses to hard...,Drama
7951,Problem Child,Ben Healy and his social climbing wife Flo ado...,"Comedy, Family"
1061,The Longest Day,"The retelling of June 6, 1944, from the perspe...","War, Action, Drama"
6225,Grandma's Boy,"Even though he's 35, Alex acts more like he's ...",Comedy
3147,Law of Desire,"Pablo, a successful film director, disappointe...","Drama, Romance, Thriller, Comedy"

In [7]:
# rows and colums
df.shape

(9000, 3)

In [8]:
# Columns
df.columns

Index(['movie', 'description', 'gener'], dtype='object')

In [9]:
# datatype
df.dtypes

movie          object
description    object
gener          object
dtype: object

In [10]:
# Checking non null values
df.isnull().sum()

movie          0
description    2
gener          2
dtype: int64

In [11]:
# Checking all null values
df[df.isnull().any(axis=1)]

,movie,description,gener
4031,Return,Return is a methodical construction of the app...,NaN
5618,Return,Eyüp decides to cross mount Ararat looking for...,NaN
6834,Return,NaN,"Drama, Fantasy"
6890,Ret,NaN,"Drama, History"

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8990 entries, 0 to 8999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movie        8990 non-null   object
 1   description  8990 non-null   object
 2   gener        8990 non-null   object
dtypes: object(3)
memory usage: 280.9+ KB

# __Data Cleaning__

In [12]:
# puting placeholder in place of Nan

df['description']= df['description'].fillna("No description avalible")
df['gener'] = df['gener'].fillna('Empy gener')

In [13]:
# Checking null values
df.isnull().sum()

movie          0
description    0
gener          0
dtype: int64

In [14]:
# Checking duplicates
df.duplicated().sum()

np.int64(10)

In [15]:
# Printing duplicates
df[df.duplicated()]

,movie,description,gener
2309,Little Women,Four sisters come of age in America in the aft...,"Drama, Romance"
3088,Lolita,Humbert Humbert is a middle-aged British novel...,Drama
4640,Cold Storage,"When a mutating, highly contagious fungus esca...","Horror, Science Fiction, Comedy"
5180,Cul-de-sac,"On the run and in search of help, two wounded ...","Thriller, Comedy, Crime, Drama"
5573,Wuthering Heights,Young orphan Heathcliff is adopted by the weal...,"Drama, Romance"
5840,Torn Curtain,"During the Cold War, an American scientist app...",Thriller
6780,Two Night Stand,After an extremely regrettable one night stand...,"Romance, Comedy"
7880,"Yours, Mine & Ours",Admiral Frank Beardsley returns to New London ...,"Comedy, Family, Romance"
8049,The Producers,A conniving Broadway producer and his meek acc...,Comedy
8680,6 Souls,A female forensic psychiatrist discovers that ...,"Horror, Mystery, Thriller"

In [17]:
# incepecting duplicates
df[df.duplicated(keep=False)].head(10)

,movie,description,gener
549,Little Women,Four sisters come of age in America in the aft...,"Drama, Romance"
2162,Lolita,Humbert Humbert is a middle-aged British novel...,Drama
2309,Little Women,Four sisters come of age in America in the aft...,"Drama, Romance"
2693,Wuthering Heights,Young orphan Heathcliff is adopted by the weal...,"Drama, Romance"
3088,Lolita,Humbert Humbert is a middle-aged British novel...,Drama
3305,The Producers,A conniving Broadway producer and his meek acc...,Comedy
4608,Cold Storage,"When a mutating, highly contagious fungus esca...","Horror, Science Fiction, Comedy"
4640,Cold Storage,"When a mutating, highly contagious fungus esca...","Horror, Science Fiction, Comedy"
5179,Cul-de-sac,"On the run and in search of help, two wounded ...","Thriller, Comedy, Crime, Drama"
5180,Cul-de-sac,"On the run and in search of help, two wounded ...","Thriller, Comedy, Crime, Drama"

In [18]:
# Removing duplicates
df = df.drop_duplicates()

In [19]:
# Verifying
df.duplicated().sum()

np.int64(0)

In [ ]:
# Checking empty string
df['description'].eq('').sum()

np.int64(0)

In [30]:
df['movie'].eq('').sum()

np.int64(0)

In [31]:
df['gener'].eq('').sum()

np.int64(0)

In [24]:
# Checking for duplicates movie title

df['movie'].duplicated().sum()

np.int64(284)

In [26]:
# Incepecting duplicates

df[df['movie'].duplicated(keep=False)].head(20)

,movie,description,gener
9,12 Angry Men,The defense and the prosecution have rested an...,Drama
48,Whiplash,"Under the direction of a ruthless instructor, ...","Drama, Music, Thriller"
89,Obsession,"After breaking the mysterious ""One Wish Willow...","Horror, Thriller"
90,Miracle in Cell No. 7,"Separated from his daughter, a father with an ...",Drama
91,The Lion King,"Young lion prince Simba, eager to one day beco...","Animation, Family, Drama"
106,Gladiator,"After the death of Emperor Marcus Aurelius, hi...","Action, Drama, Adventure"
161,Scarface,After getting a green card in exchange for ass...,"Action, Crime, Drama"
169,The Kid,A tramp cares for a boy after he's abandoned a...,"Comedy, Drama"
198,The Hunt,"A teacher lives a lonely life, all the while s...",Drama
211,Metropolis,In a futuristic city sharply divided between t...,"Drama, Science Fiction"
227,The Thing,A research team in Antarctica is hunted by a s...,"Horror, Mystery, Science Fiction"
298,The Wages of Fear,"In a run-down South American town, four men ar...","Drama, Thriller, Adventure"
331,Black Beauty,"Born free in the American West, Black Beauty i...",Drama
362,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...","Adventure, Action, Fantasy"
384,How to Train Your Dragon,"On the rugged isle of Berk, where Vikings and ...","Fantasy, Family, Action, Adventure"
402,Ghost in the Shell,"In the year 2029, the barriers of our world ha...","Action, Animation, Science Fiction"
406,Monster,"After an outburst at school involving her son,...","Mystery, Thriller, Drama"
410,The Postman,Simple Italian postman learns to love poetry w...,"Comedy, Drama, Romance"
418,My Way,During the invasion of Normandy the photograph...,"Drama, Action, History, War"
443,Mulan,When Imperial China calls one man from every f...,"Animation, Family, Adventure"

In [ ]:
duplicates = df[df['movie'].duplicated(keep=False)]
duplicates[['movie']].sort_values('movie')

                  movie
9          12 Angry Men
841        12 Angry Men
2278       3:10 to Yuma
2536       3:10 to Yuma
1524  A Christmas Carol
...                 ...
6842                  X
5928                  Z
668                   Z
5363               Zulu
1866               Zulu

[532 rows x 1 columns]

In [28]:
# droping the duplicates movies

df = df.drop_duplicates(subset=['movie'])

In [29]:
# checking duplicates again
df['movie'].duplicated().sum()

np.int64(0)