In [1]:
import numpy as np
import pandas as pd

# __Load Dataset__

In [2]:
df = pd.read_csv(r'C:\Users\ibad\Desktop\NLP_Notes\projects\project1\data\tmdb_9000_top_rated.csv')

# __EDA Process__

In [3]:
# Understanding first five rows
df.head()

,movie,description,gener
0,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...","Animation, Action, Adventure, Fantasy"
1,Accidental Partners,Two women discover they were both scammed by t...,"Comedy, Romance"
2,Swapped,"A small woodland creature and a majestic bird,...","Adventure, Animation, Family, Fantasy"
3,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
4,Michael,"The story of Michael Jackson, one of the most ...","Music, Drama"

In [4]:
# Last 5 rows
df.tail()

,movie,description,gener
8995,Open Season: Scared Silly,The humans and animals believe a werewolf is o...,"Animation, Comedy, Family, Adventure, TV Movie"
8996,The Dyatlov Pass Incident,"In February of 1959, nine Russian hikers ventu...","Thriller, Mystery"
8997,Ri¢hie Ri¢h,"Billionaire heir Richie Rich has it all, inclu...","Comedy, Family"
8998,24 Hours to Live,An assassin seeks redemption after being given...,"Action, Science Fiction, Thriller, Mystery"
8999,iBoy,"After an accident, Tom wakes from a coma to di...","Action, Science Fiction"

In [12]:
# Checking random rows
df.sample(5)

,movie,description,gener
4002,Death Wish,"After his wife is murdered by street punks, a ...","Crime, Drama, Action"
780,Two Is a Family,A man without attachments or responsibilities ...,"Drama, Comedy"
1028,The Others,Grace is a woman who lives in an old house kep...,"Horror, Mystery, Thriller"
1285,Teen Titans Go! vs. Teen Titans,The comedic modern-day quintet takes on their ...,"Action, Animation, Comedy, Family, Fantasy, Sc..."
8184,Big Trouble,The story of how a mysterious suitcase brings ...,"Action, Comedy, Thriller, Mystery, Crime"

In [13]:
# rows and colums
df.shape

(9000, 3)

In [14]:
# Columns
df.columns

Index(['movie', 'description', 'gener'], dtype='object')

In [15]:
# datatype
df.dtypes

movie          object
description    object
gener          object
dtype: object

In [16]:
# Checking non null values
df.isnull().sum()

movie          0
description    2
gener          2
dtype: int64

In [ ]:
# Checking all null values
df[df.isnull().any(axis=1)]

,movie,description,gener
4031,Return,Return is a methodical construction of the app...,NaN
5618,Return,Eyüp decides to cross mount Ararat looking for...,NaN
6834,Return,NaN,"Drama, Fantasy"
6890,Ret,NaN,"Drama, History"

In [25]:
# puting placeholder in place of Nan

df['description']= df['description'].fillna("No description avalible")
df['gener'] = df['gener'].fillna('Empy gener')

In [26]:
# Checking null values
df.isnull().sum()

movie          0
description    0
gener          0
dtype: int64

In [28]:
# Checking duplicates
df.duplicated().sum()

np.int64(10)

In [29]:
# Printing duplicates
df[df.duplicated()]

,movie,description,gener
2309,Little Women,Four sisters come of age in America in the aft...,"Drama, Romance"
3088,Lolita,Humbert Humbert is a middle-aged British novel...,Drama
4640,Cold Storage,"When a mutating, highly contagious fungus esca...","Horror, Science Fiction, Comedy"
5180,Cul-de-sac,"On the run and in search of help, two wounded ...","Thriller, Comedy, Crime, Drama"
5573,Wuthering Heights,Young orphan Heathcliff is adopted by the weal...,"Drama, Romance"
5840,Torn Curtain,"During the Cold War, an American scientist app...",Thriller
6780,Two Night Stand,After an extremely regrettable one night stand...,"Romance, Comedy"
7880,"Yours, Mine & Ours",Admiral Frank Beardsley returns to New London ...,"Comedy, Family, Romance"
8049,The Producers,A conniving Broadway producer and his meek acc...,Comedy
8680,6 Souls,A female forensic psychiatrist discovers that ...,"Horror, Mystery, Thriller"

In [31]:
# Removing duplicates
df = df.drop_duplicates()